name: Trigger HakuApi Re-Deploy

on:
  push:
    branches: [ "master" ]
    paths:
      - 'EasyExtractUnitypackageRework/EasyExtract.Core/**'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger HakuApi auto-deploy webhook
        run: |
          curl -X POST https://api.github.com/repos/HakuSystems/HakuApi/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.API_TRIGGER_TOKEN }}" \
          -d '{"event_type": "core_updated"}'
